### PR TITLE
change settings delivery keys check

### PR DESCRIPTION
**Pull request by tehreem-sadat**

### CODE REVIEW

**Comment by asamolion** [comment]
Why is this change necessary?

**Comment by danialmalik** [comment]
@asamolion because in file `aws.py` the variables : 
```
CALIPER_DELIVERY_ENDPOINT = ENV_TOKENS.get('CALIPER_DELIVERY_ENDPOINT')
CALIPER_DELIVERY_AUTH_TOKEN = AUTH_TOKENS.get('CALIPER_DELIVERY_AUTH_TOKEN')
```

are present regardless of their values being in `*.env.json` and `*.auth.json` files. These variables ARE present in settings and thus `hassattr(settings,'CALIPER_DELIVERY_AUTH_TOKEN')` will return `true` even if there is no value is set for these in `*.json` files. Therefore `getattr` is better as it will check for their values instead of their presence. 
So only if these variables have some value, condition will be met and API call will be made.

**Review by asamolion — APPROVED** [review]

**Comment by asamolion** [comment]
What will happen in the case of empty strings in either or both keys?

**Comment by danialmalik** [comment]
```
if getattr(settings, 'CALIPER_DELIVERY_ENDPOINT') and getattr(settings, 'CALIPER_DELIVERY_AUTH_TOKEN'):
                deliver_caliper_event(transformed_event, event.get('event_type'))
```

The check will fail and it will not try to deliver the logs to endpoint (which would be set to blank strings in that case).

**Comment by danialmalik** [comment]
Package version should be bumped up and republished. @asamolion

**Review by danialmalik — APPROVED** [review]

**Pull request merged**
